### ISSUE TITLE
Can't display commands due to insufficient permissions

### ISSUE THREAD

**Issue by gdamou** [codinglab-io/discord-bot#92]
When writing "/" we don't have all the commands displaying : 

![image](https://github.com/codinglab-io/discord-bot/assets/46034621/b55d8ddd-2c9c-49ee-ae13-b14014519d3d)

**Comment by neolectron** [comment]
This is clearly a non intentionall bug.

`/fart` should be available for everyone to use.

I think the scope of this fix can be greater tho. I believe we should have a way to declare permissions for our slash commands, which we do not have yet.

Interesting topic that need to be discussed.

Thanks for your report!
